# Generated by Django 6.0 on 2025-12-17 04:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('address_street', models.CharField(max_length=200)),
                ('address_street2', models.CharField(blank=True, max_length=200)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', models.CharField(max_length=50)),
                ('address_zip', models.CharField(max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('pet_species', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Small Animal', 'Rabbit/Guinea Pig/Other Small Animal')], max_length=50)),
                ('specific_pet', models.CharField(blank=True, max_length=100, verbose_name='Specific Pet Name')),
                ('home_status', models.CharField(choices=[('Own', 'Own'), ('Rent', 'Rent (Landlord approval required)')], max_length=50, verbose_name='Do you own or rent?')),
                ('hours_alone', models.CharField(max_length=200, verbose_name='Hours per day pet will be left alone')),
                ('current_pets', models.TextField(blank=True, verbose_name='Current pets list')),
                ('secure_area', models.BooleanField(verbose_name='Do you have a secure, fully enclosed yard?')),
                ('fence_height', models.CharField(blank=True, max_length=200, verbose_name='Fence height and material')),
                ('yard_description', models.TextField(blank=True, verbose_name='Yard safety and shelter description')),
                ('declaration', models.BooleanField(default=False, verbose_name='I declare all information is true')),
            ],
            options={
                'verbose_name': 'Adoption Application',
                'verbose_name_plural': 'Adoption Applications',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='FosterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('address_street', models.CharField(max_length=200)),
                ('address_street2', models.CharField(blank=True, max_length=200)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', models.CharField(max_length=50)),
                ('address_zip', models.CharField(max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('foster_type', models.CharField(blank=True, choices=[('emergency', 'Emergency care only - 1-2 weeks'), ('short', 'Short Term - 2-6 Months'), ('long', 'Long Term - 6 Months +')], max_length=50)),
                ('start_date', models.CharField(blank=True, max_length=200, verbose_name='When available to start')),
                ('work_schedule', models.CharField(choices=[('Full Time from home', 'Full Time from home'), ('Full Time at a workplace', 'Full Time at a workplace'), ('Part Time', 'Part Time'), ('Casual', 'Casual'), ('Stay At Home/Retired/Not working', 'Stay At Home/Retired/Not working')], max_length=100)),
                ('alone_hours', models.CharField(blank=True, max_length=200, verbose_name='Hours pet would be alone')),
                ('medical_condition', models.BooleanField(default=False, verbose_name='Medical conditions affecting care')),
                ('residence_status', models.CharField(choices=[('Renting', 'Renting'), ('Own', 'Own'), ('Other', 'Other')], max_length=50)),
                ('rental_dogs', models.IntegerField(blank=True, null=True, verbose_name='Additional dogs approved for (if renting)')),
                ('children_status', models.CharField(max_length=50, verbose_name='Do you have children?')),
                ('occupants_list', models.TextField(verbose_name='Names and ages of people in home')),
                ('dog_size', models.CharField(blank=True, max_length=50, verbose_name='Preferred dog size')),
                ('specific_pet', models.CharField(blank=True, max_length=200, verbose_name='Specific pet to foster')),
                ('past_breeds', models.CharField(blank=True, max_length=200, verbose_name='Past breeds/types')),
                ('yard_description', models.TextField(verbose_name='Yard description and size')),
                ('fence_height', models.CharField(max_length=200, verbose_name='Fence height at lowest point')),
                ('yard_separated', models.TextField(verbose_name='Backyard separated from front yard?')),
                ('foster_inside', models.CharField(max_length=50, verbose_name='Foster allowed inside?')),
                ('sleep_location', models.CharField(max_length=200, verbose_name='Where will foster sleep?')),
                ('other_pets', models.BooleanField(default=False, verbose_name='Do you have other pets?')),
                ('other_pets_list', models.TextField(blank=True, verbose_name='List of other pets')),
                ('dog_sex', models.CharField(blank=True, max_length=50, verbose_name='Sex of your dog(s)')),
                ('dog_desexed', models.CharField(blank=True, max_length=50, verbose_name='Are dogs desexed?')),
                ('dog_friendly', models.CharField(blank=True, max_length=50, verbose_name='Friendly towards other dogs?')),
                ('dog_vax', models.CharField(blank=True, max_length=50, verbose_name='Dog vaccinations up to date?')),
                ('dog_personality', models.TextField(blank=True, verbose_name='Dog personality')),
                ('final_comment', models.TextField(blank=True, verbose_name='Final comment')),
                ('agreement', models.BooleanField(default=False, verbose_name='Agree to foster carer commitment')),
            ],
            options={
                'verbose_name': 'Foster Application',
                'verbose_name_plural': 'Foster Applications',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='FosterApplicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='foster_checks/')),
                ('image_type', models.CharField(choices=[('yard', 'Yard Photo'), ('certificate', 'Certificate Photo')], max_length=50)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='applications.fosterapplication')),
            ],
        ),
    ]
