# Generated by Django 6.0 on 2025-12-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionapplication',
            name='home_status',
            field=models.CharField(choices=[('Own', 'Own'), ('Rent', 'Rent (Landlord approval required)')], default='Own', max_length=50, verbose_name='Do you own or rent?'),
        ),
        migrations.AlterField(
            model_name='adoptionapplication',
            name='secure_area',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, verbose_name='Do you have a secure, fully enclosed yard?'),
        ),
    ]
