# Generated by Django 5.2.5 on 2025-12-17 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_adoptionapplication_home_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('address_street', models.CharField(max_length=200)),
                ('address_street2', models.CharField(blank=True, max_length=200)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', models.CharField(max_length=50)),
                ('address_zip', models.CharField(max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('pet_name', models.CharField(max_length=100, verbose_name='Cat/Kitten Name')),
                ('coat_pref', models.CharField(blank=True, max_length=100)),
                ('home_status', models.CharField(max_length=100, verbose_name='Rent or Own')),
                ('property_type', models.CharField(max_length=100)),
                ('confinement', models.CharField(max_length=255, verbose_name='Where will cat be kept?')),
                ('other_pets', models.TextField(blank=True, verbose_name='Details of current pets')),
                ('adoption_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cat Adoption Application',
                'verbose_name_plural': 'Cat Adoption Applications',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='DogApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('address_street', models.CharField(max_length=200)),
                ('address_street2', models.CharField(blank=True, max_length=200)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', models.CharField(max_length=50)),
                ('address_zip', models.CharField(max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('pet_name', models.CharField(max_length=100, verbose_name='Dog/Puppy Name')),
                ('dog_size_pref', models.CharField(max_length=100, verbose_name='Preferred Adult Size')),
                ('breed_experience', models.TextField(verbose_name='Experience with this breed')),
                ('yard_size', models.CharField(max_length=100)),
                ('fencing_secure', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('fence_details', models.CharField(max_length=255, verbose_name='Fence height/material')),
                ('hours_alone', models.CharField(max_length=100)),
                ('work_status', models.CharField(max_length=100)),
                ('sleeping_location', models.CharField(max_length=255)),
                ('training_plan', models.CharField(max_length=255)),
                ('adjustment_plan', models.TextField(blank=True, verbose_name='Plan for adjustment period')),
                ('rehome_history', models.TextField(blank=True, verbose_name='Previous rehoming history')),
            ],
            options={
                'verbose_name': 'Dog Adoption Application',
                'verbose_name_plural': 'Dog Adoption Applications',
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.DeleteModel(
            name='AdoptionApplication',
        ),
    ]
