# Generated by Django 5.2.5 on 2025-12-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_catapplication_dogapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catapplication',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='age_confirm',
            field=models.CharField(blank=True, max_length=10, verbose_name='18 years or older?'),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='allergies',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='allow_inside',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='children_education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='coat_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='confinement_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='considered_fostering',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='employment_length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='food_plan',
            field=models.CharField(blank=True, max_length=200, verbose_name='Food plan'),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='heard_about',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='heard_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='home_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='household_agreement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='household_members',
            field=models.TextField(blank=True, verbose_name='Names and ages of household members'),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='introducing_to_existing',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='main_caregiver',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='other_animals_desexed',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='property_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='provide_pictures',
            field=models.CharField(blank=True, max_length=10, verbose_name='Happy to provide pictures'),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='readiness',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='readiness_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='reason_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='reference_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='rehome_other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='rehomed_before',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='residence_length',
            field=models.CharField(blank=True, max_length=50, verbose_name='How long lived in current home'),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='vet_care_importance',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='work_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='catapplication',
            name='work_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='adoption_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='age_confirm',
            field=models.CharField(blank=True, max_length=10, verbose_name='18 years or older?'),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='allergies',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='children_education',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='command_experience',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='considered_fostering',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='daily_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Daily time with dog'),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='employment_length',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='entertainment_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='fencing_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='food_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='food_plan',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='heard_about',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='heard_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='home_check_ok',
            field=models.CharField(blank=True, max_length=10, verbose_name='Happy for home check?'),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='home_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='home_status',
            field=models.CharField(default='Own', max_length=200, verbose_name='Rent or Own'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='household_agreement',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='household_members',
            field=models.TextField(blank=True, verbose_name='Names and ages of household members'),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='inside_outside',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='main_caregiver',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='other_animals_desexed',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='other_pets_list',
            field=models.TextField(blank=True, verbose_name='Other pets list'),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='personality_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Indoors/outdoors person'),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='property_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='property_type',
            field=models.CharField(default='Own', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='readiness',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='readiness_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='reason_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='reference_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='rehomed_before',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='residence_length',
            field=models.CharField(blank=True, max_length=50, verbose_name='How long lived in current home'),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='size_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='toilet_training_experience',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='training_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='vet_care_importance',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='walking_frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='work_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Where dog while at work'),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='work_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dogapplication',
            name='yard_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='catapplication',
            name='home_status',
            field=models.CharField(max_length=200, verbose_name='Rent or Own'),
        ),
        migrations.AlterField(
            model_name='dogapplication',
            name='fencing_secure',
            field=models.CharField(max_length=20, verbose_name='Fully fenced and secure?'),
        ),
        migrations.AlterField(
            model_name='dogapplication',
            name='training_plan',
            field=models.CharField(max_length=200),
        ),
    ]
