# Generated by Django 5.2.5 on 2025-12-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_catapplication_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fosterapplicationimage',
            name='date_uploaded',
        ),
        migrations.AddField(
            model_name='fosterapplication',
            name='residence_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fosterapplication',
            name='work_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='agreement',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='alone_hours',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='children_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='dog_desexed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='dog_friendly',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='dog_personality',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='dog_sex',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='dog_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='dog_vax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='fence_height',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='final_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='foster_inside',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='foster_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='medical_condition',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='occupants_list',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='other_pets',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='other_pets_list',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='past_breeds',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='rental_dogs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='residence_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='sleep_location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='specific_pet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='start_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='work_schedule',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='yard_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fosterapplication',
            name='yard_separated',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fosterapplicationimage',
            name='image',
            field=models.ImageField(upload_to='foster_uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='fosterapplicationimage',
            name='image_type',
            field=models.CharField(choices=[('yard', 'Yard'), ('vax', 'Vaccination')], max_length=20),
        ),
    ]
