# Generated by Django 5.2.5 on 2025-12-25 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_remove_fosterapplicationimage_date_uploaded_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurrenderApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mobile", models.CharField(max_length=20)),
                ("address_street", models.CharField(max_length=200)),
                ("address_street2", models.CharField(blank=True, max_length=200)),
                ("address_city", models.CharField(max_length=100)),
                ("address_state", models.CharField(max_length=50)),
                ("address_zip", models.CharField(max_length=20)),
                (
                    "age",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(18)]
                    ),
                ),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("pet_name", models.CharField(max_length=100)),
                ("breed", models.CharField(max_length=100)),
                ("size", models.CharField(max_length=50)),
                ("legal_owner", models.CharField(max_length=50)),
                ("legal_owner_details", models.TextField(blank=True)),
                ("microchip_number", models.CharField(max_length=50)),
                ("last_vaccination", models.CharField(max_length=100)),
                ("desexed", models.CharField(max_length=20)),
                ("is_wormed", models.BooleanField(default=True)),
                ("heartworm_preventative", models.BooleanField(default=False)),
                ("living_with_dogs", models.CharField(max_length=20)),
                ("dog_sizes_exposed", models.CharField(max_length=100)),
                ("dog_friendly", models.CharField(max_length=100)),
                ("cat_friendly", models.CharField(max_length=100)),
                ("living_with_children", models.CharField(max_length=20)),
                ("child_ages", models.CharField(blank=True, max_length=100)),
                ("living_arrangements", models.TextField()),
                ("toilet_trained", models.CharField(max_length=50)),
                ("behavioral_issues", models.TextField()),
                ("food_aggression", models.CharField(max_length=100)),
                ("fear_triggers", models.TextField()),
                ("commands", models.TextField()),
                ("meeting_strangers", models.TextField()),
                ("travel_well", models.CharField(max_length=100)),
                ("walks_well", models.CharField(max_length=100)),
                ("yard_type", models.CharField(max_length=100)),
                ("fencing_details", models.TextField()),
                ("current_diet", models.CharField(max_length=255)),
                ("diet_other_details", models.TextField(blank=True)),
                ("contact_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("reason", models.TextField()),
                ("time_in_care", models.CharField(max_length=100)),
                ("urgency", models.CharField(max_length=100)),
                ("urgency_other_details", models.TextField(blank=True)),
                (
                    "preference",
                    models.TextField(verbose_name="Preference for new home"),
                ),
                ("blurb", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Surrender Application",
                "verbose_name_plural": "Surrender Applications",
                "ordering": ["-date_submitted"],
            },
        ),
    ]
