# Generated by Django 5.2.5 on 2025-12-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_surrenderapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="surrenderapplication",
            name="age_group",
            field=models.CharField(
                default="Unknown", max_length=50, verbose_name="Pet Age Group"
            ),
            preserve_default=False,
        ),
    ]
