# Generated by Django 5.2.5 on 2025-12-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_surrenderapplication_age_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surrenderapplication",
            name="age_group",
        ),
        migrations.AddField(
            model_name="surrenderapplication",
            name="approximate_dob",
            field=models.BooleanField(default=False, verbose_name="Approximate DOB"),
        ),
        migrations.AddField(
            model_name="surrenderapplication",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
    ]
