# Generated by Django 5.2.5 on 2025-12-25 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_remove_surrenderapplication_age_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surrenderapplication",
            name="age",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(18)],
            ),
        ),
        migrations.AlterField(
            model_name="surrenderapplication",
            name="approximate_dob",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="surrenderapplication",
            name="dob",
            field=models.DateField(
                blank=True, null=True, verbose_name="Animal Date of Birth"
            ),
        ),
    ]
