# Generated by Django 5.2.5 on 2025-12-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_surrenderapplication_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surrenderapplication',
            name='contact_name',
        ),
        migrations.AlterField(
            model_name='surrenderapplication',
            name='last_vaccination',
            field=models.DateField(blank=True, null=True, verbose_name='Date of last Vaccination'),
        ),
    ]
