# Generated by Django 6.0 on 2025-12-17 04:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('species', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Other', 'Other')], max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('approximate_dob', models.BooleanField(default=False, verbose_name='Approximate DOB')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XLarge', 'Extra Large')], max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('adoption_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available Now'), ('SOON', 'Available Soon'), ('PENDING', 'Pending Adoption'), ('ADOPTED', 'Adopted'), ('NOT_AVAILABLE', 'Not Available')], default='AVAILABLE', max_length=20)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='animal_photos/')),
                ('description', models.TextField()),
                ('good_with_kids', models.BooleanField(default=False)),
                ('special_needs', models.BooleanField(default=False)),
                ('microchipped', models.BooleanField(default=False)),
                ('vaccinated', models.BooleanField(default=False)),
                ('desexed', models.BooleanField(default=False)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Animal Profile',
                'verbose_name_plural': 'Animal Profiles',
                'ordering': ['-date_entered'],
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animal_photos/gallery/')),
                ('order', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='animals.animalprofile')),
            ],
            options={
                'ordering': ['order', 'date_added'],
            },
        ),
    ]
