# Generated by Django 5.2.5 on 2025-12-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalimage',
            name='microchip_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='animalimage',
            name='microchipped',
            field=models.BooleanField(default=False),
        ),
    ]
