# Generated by Django 5.2.5 on 2025-12-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animalimage_microchip_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalprofile',
            name='microchip_number',
            field=models.CharField(blank=True, help_text='Enter the 15-digit microchip number', max_length=50, null=True),
        ),
    ]
