# Generated by Django 5.2.5 on 2025-12-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0003_animalprofile_microchip_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="animalprofile",
            name="blurb",
            field=models.CharField(
                blank=True,
                help_text="A short catchy line for the top of the page.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="good_with_cats",
            field=models.BooleanField(default=False, verbose_name="Good with Cats"),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="good_with_dogs",
            field=models.BooleanField(default=False, verbose_name="Good with Dogs"),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="heartworm_preventative",
            field=models.BooleanField(
                default=False, verbose_name="Heartworm Preventative Received"
            ),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="interstate_allowed",
            field=models.BooleanField(
                default=False, verbose_name="Interstate Adoption Available"
            ),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="is_wormed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="kids_5_to_12",
            field=models.BooleanField(
                default=False, verbose_name="Suitable for Kids 5-12"
            ),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="kids_under_5",
            field=models.BooleanField(
                default=False, verbose_name="Suitable for Kids Under 5"
            ),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="state_act",
            field=models.BooleanField(default=False, verbose_name="ACT"),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="state_nsw",
            field=models.BooleanField(default=True, verbose_name="NSW"),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="state_qld",
            field=models.BooleanField(default=False, verbose_name="QLD"),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="state_sa",
            field=models.BooleanField(default=False, verbose_name="SA"),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="state_tas",
            field=models.BooleanField(default=False, verbose_name="TAS"),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="state_vic",
            field=models.BooleanField(default=False, verbose_name="VIC"),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="state_wa",
            field=models.BooleanField(default=False, verbose_name="WA"),
        ),
    ]
