# Generated by Django 5.2.5 on 2025-12-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0004_animalprofile_blurb_animalprofile_good_with_cats_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animalprofile",
            name="interstate_allowed",
        ),
        migrations.RemoveField(
            model_name="animalprofile",
            name="state_act",
        ),
        migrations.RemoveField(
            model_name="animalprofile",
            name="state_nsw",
        ),
        migrations.RemoveField(
            model_name="animalprofile",
            name="state_qld",
        ),
        migrations.RemoveField(
            model_name="animalprofile",
            name="state_sa",
        ),
        migrations.RemoveField(
            model_name="animalprofile",
            name="state_tas",
        ),
        migrations.RemoveField(
            model_name="animalprofile",
            name="state_vic",
        ),
        migrations.RemoveField(
            model_name="animalprofile",
            name="state_wa",
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="act",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="interstate_adoption",
            field=models.BooleanField(
                default=False, help_text="Unchecked means NSW Only"
            ),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="nsw",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="qld",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="sa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="tas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="vic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animalprofile",
            name="wa",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="animalprofile",
            name="desexed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="animalprofile",
            name="good_with_cats",
            field=models.BooleanField(
                default=False, verbose_name="Good with other Cats"
            ),
        ),
        migrations.AlterField(
            model_name="animalprofile",
            name="good_with_dogs",
            field=models.BooleanField(
                default=False, verbose_name="Good with other Dogs"
            ),
        ),
        migrations.AlterField(
            model_name="animalprofile",
            name="microchipped",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="animalprofile",
            name="vaccinated",
            field=models.BooleanField(default=True),
        ),
    ]
