# Generated by Django 5.2.5 on 2025-12-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_remove_animalprofile_interstate_allowed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalprofile',
            name='weight_kg',
        ),
    ]
